---
# tasks file for webserver
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - apache2
    - mysql-client
    - php5-mysql
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - python-mysqldb
    - php5-gd
    - libssh2-php

- name: check is /srv/web exists
  stat: path=/srv/web
  register: webdir

- name: create filesystem on /dev/vdb
  shell: 'parted -s -a optimal /dev/vdb mklabel msdos; parted -s -a optimal -- /dev/vdb unit compact mkpart primary ext3 1 -1; mkfs.ext3 /dev/vdb1'
  args:
      creates: /root/create.vdb
  when: webdir.stat.isdir is not defined
  tags:
    - add_volume

- name: mount /dev/vdb on /srv
  shell: 'echo "/dev/vdb1 /srv ext3 rw 0 0" >> /etc/fstab; mount -a'
  args:
      creates: /root/mount.vdb
  when: webdir.stat.isdir is not defined
  tags:
    - add_volume

- name: create directories on /srv for web
  shell: 'mkdir -p /srv/web/'
  args:
      creates: /srv/web
  when: webdir.stat.isdir is not defined

- name: enabling php5-mcrypt in apache2
  command: php5enmod mcrypt
  notify:
    - restart apache
